### ISSUE TITLE
Notice: Constant _AM_ERROR_NOFRAMEWORKS already defined

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/suico#182]
when using module like slideshow countdown i received this error . 

Notice: Constant _AM_ERROR_NOFRAMEWORKS already defined in file /modules/suico/language/english/admin.php line 297

**Comment by mambax7** [comment]
This define(): 
`define('_AM_ERROR_NOFRAMEWORKS', 'Error: You don&#39;t use the Frameworks \'admin module\'. Please install this Frameworks');`
can be removed from every module, as it is not needed anymore. 
And because it is the same, it creates a conflict.  That's why all define() should be unique and use the name of the module in the name, e.g.  "_AM_COUNTDOWN_MAINTAINEDBY"
